[package]
name = "christianguide"
version = "0.1.0"
edition = "2021"
Aurthor = "Conor Stinson"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = "0.3"
eframe = "0.19.0"
